### ISSUE TITLE
how do i use it?

### ISSUE THREAD

**Issue by tetrdd** [quarterwave0/BeamNG-ADAS#1]
i would really like to use this, but how canm i install this?

**Comment by quarterwave0** [comment]
Here's the thing -- this was an experimental project I did to gain more familiarity with the technologies included in it. It's not as good as you think it is, and it is very unwieldy to operate and specialized in focus. This would all need set up with what I remember this to be a python 3.8 or 3.9 venv, as well as OBS and a windows system to run this all on, since vgamepad requires it.

Bottom line, this isn't really something you can download easily. A reimplementation in something like Carla would likely be easier to work with, but it's not worth porting.
